version: "3"

services:
  nginx:
    image: nginx:${DOCKER_NGINX_VERSION}-alpine
    ports:
      - ${DOCKER_EXTERNAL_PORT}:80    
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./srcPHP:/var/www/php.test
      - ./srcJS:/var/www/js.test
    links:
      - php
  
  php:
    image: php:${DOCKER_PHP_VERSION}-fpm-alpine
    volumes:
      - ./srcPHP:/var/www/php.test
